### ISSUE TITLE
asking about default password

### ISSUE THREAD

**Issue by BoniWPy** [haxorsprogramming/Point-Of-Sales#1]
when i wanna login into applicaton, the password is?

**Comment by BoniWPy** [comment]
the owner repo has been died. RIP

**Comment by haxorsprogramming** [comment]
look the seed .... u can migrate & seed to the table user

**Comment by BoniWPy** [comment]
yes i did, but the href on login page not direct to another.
i'm sorry, i'm a newbie on laravel, i can't set href direction. ~_~

on loginPage.blade.php line 47 href="#!">Masuk</a>

Thanks for your reply. Great day
